import { useLiveQuery } from 'dexie-react-hooks';
import { CloudUpload, RefreshCw, RotateCcw } from 'lucide-react';
import { useState } from 'react';
import { PageHeader } from '../components/PageHeader';
import { StatusBadge } from '../components/StatusBadge';
import { db } from '../lib/db';
import { firebaseEnabled } from '../lib/firebase';
import { resetDemoData } from '../lib/repository';
import { flushSyncQueue } from '../lib/sync';
export default function SyncPage(){const queue=useLiveQuery(()=>db.syncQueue.orderBy('createdAt').reverse().toArray(),[])??[]; const audits=useLiveQuery(()=>db.syncAudit.orderBy('syncedAt').reverse().limit(8).toArray(),[])??[]; const [msg,setMsg]=useState(''); const [busy,setBusy]=useState(false); const sync=async()=>{setBusy(true);try{const r=await flushSyncQueue();setMsg(r.message)}finally{setBusy(false)}};return <div className="mx-auto max-w-7xl p-4 sm:p-6 lg:p-8"><PageHeader eyebrow="Offline-first operations" title="Sync queue" description="Writes stay local until they can be safely pushed into the shared Firestore business namespace." action={<div className="flex gap-2"><button className="btn-secondary" onClick={async()=>{await resetDemoData();setMsg('Demo data reset.')}}><RotateCcw className="size-4"/>Reset sample data</button><button className="btn-primary" onClick={sync} disabled={busy}><CloudUpload className="size-4"/>{busy?'Syncing…':'Sync now'}</button></div>}/>
  <div className="grid gap-4 xl:grid-cols-[1.2fr_.8fr]"><div className="card p-5"><div className="flex items-center justify-between"><h2 className="text-sm font-semibold text-white">Pending changes</h2><StatusBadge tone={queue.length?'warn':'good'}>{queue.length} queued</StatusBadge></div>{msg&&<p className="mt-3 rounded-2xl bg-blue-600/10 p-3 text-xs text-blue-200">{msg}</p>}<div className="mt-4 space-y-2">{queue.length?queue.slice(0,20).map(q=><div key={q.id} className="rounded-2xl border border-slate-800 bg-slate-950/60 p-3"><div className="flex items-center justify-between"><p className="text-xs font-medium text-slate-300">{q.collection} / {q.docId}</p><StatusBadge tone={q.status==='failed'?'bad':'warn'}>{q.status}</StatusBadge></div><p className="mt-1 text-[11px] text-slate-600">Attempts {q.attempts}{q.lastError?` · ${q.lastError.slice(0,90)}`:''}</p></div>):<div className="rounded-2xl border border-dashed border-slate-800 p-8 text-center text-xs text-slate-500">Nothing waiting to sync.</div>}</div></div>
  <div className="space-y-4"><div className="card p-5"><div className="flex items-center gap-2"><RefreshCw className="size-4 text-blue-400"/><h2 className="text-sm font-semibold text-white">Mode</h2></div><p className="mt-3 text-xs leading-6 text-slate-400">{firebaseEnabled?'Firebase configuration is enabled. Sync still requires an authenticated member from the shared platform shell.':'Standalone test harness is active. Local writes are retained until the final shared Firebase adapter is connected.'}</p></div><div className="card p-5"><h2 className="text-sm font-semibold text-white">Recent sync audit</h2><div className="mt-3 space-y-2">{audits.length?audits.map(a=><p key={a.id} className="rounded-xl bg-slate-950/60 px-3 py-2 text-[11px] text-slate-500">{a.collection} · {new Date(a.syncedAt).toLocaleString()}</p>):<p className="text-xs text-slate-600">No cloud sync completed yet.</p>}</div></div></div></div>
</div>}
